import type { Product } from './types';

export const products: Product[] = [
  {
    id: 'geo-abstract',
    name: 'Geometric Abstract Tee',
    description: 'Bold and modern.',
    longDescription: 'Make a statement with this t-shirt featuring a vibrant and colorful geometric abstract design. Perfect for art lovers and those who appreciate modern aesthetics. Made from 100% soft-touch cotton.',
    price: 29.99,
    sizes: ['S', 'M', 'L', 'XL'],
    imageId: 'tshirt-geo-abstract',
    imageHint: 'geometric tshirt',
  },
  {
    id: 'minimal-wave',
    name: 'Minimal Wave Tee',
    description: 'Simple and elegant.',
    longDescription: 'Embrace simplicity with this white t-shirt showcasing a single, elegant black wave line. A versatile piece that pairs well with anything, embodying the "less is more" philosophy.',
    price: 24.99,
    sizes: ['S', 'M', 'L'],
    imageId: 'tshirt-minimal-wave',
    imageHint: 'minimalist tshirt',
  },
  {
    id: 'vintage-logo',
    name: 'Vintage Logo Tee',
    description: 'Retro and cool.',
    longDescription: 'A throwback to classic style, this heather gray t-shirt has a distressed, vintage-inspired logo that gives it a perfectly worn-in feel. Ideal for a relaxed, casual look.',
    price: 27.50,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    imageId: 'tshirt-vintage-logo',
    imageHint: 'vintage tshirt',
  },
  {
    id: 'botanical-print',
    name: 'Botanical Print Tee',
    description: 'Inspired by nature.',
    longDescription: 'Connect with nature with this forest green t-shirt adorned with a detailed botanical leaf print. It\'s a subtle yet beautiful design for plant enthusiasts and nature lovers.',
    price: 32.00,
    sizes: ['M', 'L', 'XL'],
    imageId: 'tshirt-botanical',
    imageHint: 'botanical print',
  },
  {
    id: 'space-explorer',
    name: 'Space Explorer Tee',
    description: 'For the adventurers.',
    longDescription: 'Fuel your curiosity for the cosmos with this navy blue t-shirt. The retro design featuring an astronaut and planets is perfect for dreamers and space explorers alike.',
    price: 35.00,
    sizes: ['S', 'M', 'L', 'XL'],
    imageId: 'tshirt-space-explorer',
    imageHint: 'space tshirt',
  },
  {
    id: 'cityscape-lines',
    name: 'Cityscape Lines Tee',
    description: 'Urban and stylish.',
    longDescription: 'Capture the energy of the city with this charcoal t-shirt. It features a stylized line art of a city skyline at night, perfect for the urban dweller with a sense of style.',
    price: 28.99,
    sizes: ['S', 'M', 'L'],
    imageId: 'tshirt-cityscape',
    imageHint: 'cityscape tshirt',
  },
  {
    id: 'striped-classic',
    name: 'Striped Classic Tee',
    description: 'Timeless and versatile.',
    longDescription: 'You can\'t go wrong with a classic. This navy and white striped t-shirt is a timeless piece that offers effortless style. Made from a comfortable cotton blend for all-day wear.',
    price: 22.99,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    imageId: 'tshirt-striped-classic',
    imageHint: 'striped shirt',
  },
  {
    id: 'plain-black',
    name: 'Essential Black Tee',
    description: 'A wardrobe staple.',
    longDescription: 'The perfect foundation for any outfit. This high-quality, plain black t-shirt is made from premium, heavyweight cotton for a structured and comfortable fit that lasts.',
    price: 19.99,
    sizes: ['S', 'M', 'L', 'XL'],
    imageId: 'tshirt-plain-black',
    imageHint: 'black tshirt',
  },
  {
    id: 'origami-crane',
    name: 'Origami Crane Tee',
    description: 'Peace and simplicity.',
    longDescription: 'A symbol of peace and hope, the single origami crane graphic on this light-gray shirt offers a touch of delicate artistry. A simple, meaningful design for everyday wear.',
    price: 26.00,
    sizes: ['S', 'M', 'L'],
    imageId: 'tshirt-origami-crane',
    imageHint: 'origami tshirt',
  },
];
